export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
